from examples.my_agent.my_agent_1.macro_action import *

economic_action = [
    doNothing,
    buildSupplydepot,
    buildBarracks,
    buildBarracksReactor,
    buildBarracksTechlab,
    liftBarracks,
    landAndReadyToBuildBarracksAddOn,
    buildEngineeringbay,
    buildRefinery,
    # buildFactory,
    # buildFactoryReactor,
    # buildFactoryTechlab,
    # liftFactory,
    # landAndReadyToBuildFactoryAddOn,
    # buildGhostAcademy,
    # buildMissileturret,
    # buildSensortower,
    # buildBunker,
    # buildArmory,
    # buildFusioncore,
    # buildStarport,
    # buildStarportReactor,
    # buildStarportTechlab,
    # liftStarport,
    # landAndReadyToBuildStarportAddOn,

    upgradeInfantryWeaponsLevel1,
    upgradeInfantryArmorLevel1,
    # upgradeInfantryWeaponsLevel2,
    # upgradeInfantryArmorLevel2,
    # upgradeInfantryWeaponsLevel3,
    # upgradeInfantryArmorLevel3,

    upgradeCombatShield,
    upgradeConcussiveshells,
    expand,

    trainScv,
    trainMarine,
    trainMarauder,
    # trainGhost,
    # trainViking,
    # trainThor,
    # trainRaven,
    # trainMedivac,
    # trainBanshee,
    # trainWidowmine,
    # trainLiberator,
    # trainCyclone,
    # trainSiegetank,
    # trainBattlecruiser,
    # trainHellion,

    scvBackToWork,
    detectionAndAttack,
    massNearEnemyBase,
    # massNearBase,
    retreat,
    defence,
    attackEnemySquad,
    attackNearestBase
]
